# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b4ee3124470a7eca3462730b55491bafce7c6374455c4bc83fd627e0af0d0a17744b98978e33dafc4aa734c45aae5c7741eb4f5a1089f8dd30ae8dfd9324e3

test:
  secret_key_base: 1a9c7a46f7c51384bc93d97ed52baca04dff7a445bd21386d36cac6d8f627235c0f9da2adaf13e54cd6c778be776b75b72a50fd71c34f58c135e8acf579afb61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
